# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 11:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.WebsiteCategory'),
        ),
        migrations.DeleteModel(
            name='WebsiteCategory',
        ),
    ]
