# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_auto_20170409_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='url',
            field=models.URLField(unique=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Website', verbose_name='website'),
        ),
        migrations.AlterField(
            model_name='website',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.WebsiteCategory', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='website',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='website',
            name='url',
            field=models.URLField(unique=True, verbose_name='url'),
        ),
    ]
